//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceConverter")]
    public interface IServiceConverter
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConverter/ConvertCurrencyToWords", ReplyAction="http://tempuri.org/IServiceConverter/ConvertCurrencyToWordsResponse")]
        string ConvertCurrencyToWords(decimal currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConverter/ConvertCurrencyToWords", ReplyAction="http://tempuri.org/IServiceConverter/ConvertCurrencyToWordsResponse")]
        System.Threading.Tasks.Task<string> ConvertCurrencyToWordsAsync(decimal currency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiceConverterChannel : ServiceReference1.IServiceConverter, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceConverterClient : System.ServiceModel.ClientBase<ServiceReference1.IServiceConverter>, ServiceReference1.IServiceConverter
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceConverterClient() : 
                base(ServiceConverterClient.GetDefaultBinding(), ServiceConverterClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceConverter.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceConverterClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceConverterClient.GetBindingForEndpoint(endpointConfiguration), ServiceConverterClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceConverterClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceConverterClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceConverterClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceConverterClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string ConvertCurrencyToWords(decimal currency)
        {
            return base.Channel.ConvertCurrencyToWords(currency);
        }
        
        public System.Threading.Tasks.Task<string> ConvertCurrencyToWordsAsync(decimal currency)
        {
            return base.Channel.ConvertCurrencyToWordsAsync(currency);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceConverter))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceConverter))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60439/CurrencyConverter.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceConverterClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceConverter);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceConverterClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceConverter);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceConverter,
        }
    }
}
